image: "python:3.7"

test_backend:
  stage: test
  script:
    - cd backend
    - pip install pytest
    - pip install -r requirements.txt
    - pytest tests
  
test_frontend:
  stage: test
    - cd frontend
    - npm install
    - elm-app test