

test-backend:
  stage: test
  image: python:3.7
  script:
    - cd backend
    - pip install pytest
    - pip install -r requirements.txt
    - pytest tests

test-frontend:
  stage: test
  image: node
  script:
    - cd frontend
    - npm install
    - npm install create-elm-app
    - elm-app test

# build_backend:
#   stage: build

# build_frontend:
#   stage: build