version: "3.7"
services:
  backend:
    build: backend
    ports:
      - "5000:5000"
  frontend:
    build: 
      context: frontend
      args:
        - MODE=development
    ports:
      - "8080:80"
